# Generated by Django 5.0.3 on 2026-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="daily_goal_hours",
        ),
        migrations.AddField(
            model_name="user",
            name="consistency_goal",
            field=models.IntegerField(default=80),
        ),
    ]
