# Generated by Django 6.0 on 2026-02-02 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities__user_id_ebfa9d_idx",
            old_name="activities_u_user_id_2e526f_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities__user_id_c100c2_idx",
            old_name="activities_u_user_id_043456_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="color_hex",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="color_hex must be a hex color like #RRGGBB",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
