# Generated by Django 5.0.3 on 2026-02-03 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0002_rename_activities_u_user_id_2e526f_idx_activities__user_id_ebfa9d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__user_id_ebfa9d_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__user_id_c100c2_idx",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="start_time",
        ),
        migrations.AddField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activitycompletion",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="activities.activity",
            ),
        ),
        migrations.AddIndex(
            model_name="activitycompletion",
            index=models.Index(
                fields=["activity", "date"], name="activities__activit_6fb8ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitycompletion",
            unique_together={("activity", "date")},
        ),
    ]
