# Generated by Django 5.0.3 on 2026-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activitycompletion_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="daily_occurrences",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of times this task occurs per day"
            ),
        ),
        migrations.AddField(
            model_name="activitycompletion",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                default=1, help_text="How many occurrences completed"
            ),
        ),
    ]
