# Generated by Django 6.0 on 2026-02-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recoverycode",
            new_name="security_re_user_id_11be7e_idx",
            old_name="security_re_user_id_0b6df2_idx",
        ),
    ]
