# Generated by Django 5.0.3 on 2026-02-04 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "security",
            "0002_rename_security_re_user_id_0b6df2_idx_security_re_user_id_11be7e_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="securitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("failed_login", "Failed Login"),
                    ("login_mfa_required", "Login MFA Required"),
                    ("mfa_failed", "MFA Failed"),
                    ("mfa_enabled", "MFA Enabled"),
                    ("mfa_disabled", "MFA Disabled"),
                    ("logout", "Logout"),
                    ("webauthn_registered", "WebAuthn Registered"),
                    ("webauthn_failed", "WebAuthn Failed"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credential_id", models.CharField(max_length=255, unique=True)),
                ("public_key", models.TextField()),
                ("sign_count", models.IntegerField(default=0)),
                (
                    "credential_type",
                    models.CharField(default="public-key", max_length=255),
                ),
                ("transports", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
